# Generated by Django 3.1.7 on 2021-06-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentdetails',
            old_name='type',
            new_name='user',
        ),
    ]
