# Generated by Django 3.1.7 on 2021-06-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_auto_20210602_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='image',
            field=models.ImageField(upload_to='images/doctor/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(upload_to='images/patient/'),
        ),
    ]
