# Generated by Django 3.1.7 on 2021-06-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20210602_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='doc_id',
            new_name='doctor',
        ),
    ]
