# Generated by Django 3.1.7 on 2021-06-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_auto_20210602_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicice',
            old_name='pres_id',
            new_name='prescription_id',
        ),
    ]
