# Generated by Django 3.1.7 on 2021-06-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_auto_20210602_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicice',
            old_name='qty',
            new_name='quantity',
        ),
    ]
