# Generated by Django 3.1.7 on 2021-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_auto_20210602_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
