# Generated by Django 3.1.7 on 2021-06-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_auto_20210602_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicice',
            old_name='prescription_id',
            new_name='prescription',
        ),
    ]
