# Generated by Django 3.1.7 on 2021-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_auto_20210602_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicice',
            new_name='Medicine',
        ),
    ]
