# Generated by Django 3.1.7 on 2021-06-05 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_auto_20210602_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetails',
            name='contact_num',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{12}$')]),
        ),
    ]
