# Generated by Django 3.1.7 on 2021-06-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0017_auto_20210605_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetails',
            name='agency_name',
            field=models.CharField(max_length=120),
        ),
    ]
