# Generated by Django 3.1.7 on 2021-06-06 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0019_auto_20210606_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetails',
            name='contact_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{12}$')]),
        ),
    ]
