# Generated by Django 3.1.7 on 2021-06-06 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0020_auto_20210606_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetails',
            name='contact_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='emergency_contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{10}$')]),
        ),
    ]
