# Generated by Django 3.1.7 on 2021-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0021_auto_20210606_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='dob',
            field=models.DateField(max_length=30),
        ),
    ]
